---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${QB_DATA_PATH}/config:/config
      - ${QB_DATA_PATH}/downloads:/downloads
      - ${QB_DATA_PATH}/watch:/watch
    ports:
      - 49153:49153
      - 49153:49153/udp
      - 8080:8080
      - 6881:6881/udp
