version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - 9001:9001
    volumes:
      - ${MINIO_DATA_PATH}:/data
      - ${MINIO_CONFIG}:/root/.minio
    environment:
      MINIO_ROOT_USER: ${USER}
      MINIO_ROOT_PASSWORD: ${PASSWORD}
      VIRTUAL_HOST: ${YOUR_DOMAIN}
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: ${YOUR_DOMAIN}
      LETSENCRYPT_EMAIL: ${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy

