services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    hostname: ${HOSTNAME}
    volumes:
      - ${PATH_TO_SYNC}:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Shanghai

